# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ddamaris <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/09/04 22:20:11 by ddamaris          #+#    #+#              #
#    Updated: 2019/09/05 16:03:49 by ddamaris         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME=ft_display_file
SRCS=ft_display_file.c ft_putchar.c ft_putstr.c
OBJ=ft_display_file.o ft_putchar.o ft_putstr.o

all:
	gcc -Wall -Werror -Wextra $(SRCS) -o $(NAME)

clean:
	/bin/rm -f $(OBJ)

fclean: clean
	/bin/rm -f $(NAME)
